src/cart/urls.py
from django.urls import path 
from .views import cart , cart_add , cart_remove



app_name = 'cart'

# urlpatterns = [
    
#     path('', cart , name='cart'),

# ]


urlpatterns = [
    path('my/cart/detail/', cart, name='cart'),
    path('cart/add/<int:product_id>/', cart_add, name='cart_add'),
    path('cart/remove/<int:product_id>/', cart_remove,name='cart_remove'),
]

src/orders/urls.py
from django.urls import path
from . import views



app_name = 'orders'


urlpatterns = [
    path('create/new/order/', views.order_create, name='order_create'),
]

src/products/urls.py
from django.urls import path
from .views import index ,  product_detail




app_name = 'products'




urlpatterns = [
    path('',index,name='index'),
    path('<slug:slug>/', index,name='index'),
    path('<str:cat_slug>/<str:product_slug>/', product_detail , name='product_detail'),
    # path(''),
]

src/src/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('', include('cart.urls')),
    path('orders/', include('orders.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/cart/models.py
from itertools import product
from django.db import models
from products.models import Product

src/orders/models.py
from django.db import models
from products.models import Product




class Order(models.Model):
    full_name = models.CharField(max_length=50)
    mobile_number = models.CharField(max_length=11)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    
    class Meta:
        ordering = ('-created',)
    def __str__(self):
        return f'Order {self.id}'
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())
    
    
class OrderItem(models.Model):
    order = models.ForeignKey(Order,related_name='items',on_delete=models.CASCADE)
    product = models.ForeignKey(Product,related_name='order_items',on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    
    def __str__(self):
        return str(self.id)
    def get_cost(self):
        return self.price * self.quantity

src/products/models.py
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify



class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=200,unique=True)
    
    class Meta:
        ordering=('name',)
        verbose_name = 'category'
        verbose_name_plural = 'category'
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('products:category',args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category,related_name='products',on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    gender = models.CharField(max_length=20 , blank=True, null=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ('created',)
        index_together = (('id', 'slug'),)
        
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('products:product_detail',args=[self.slug])
    
    
# def get_image_filename(instance, filename):
#     title = instance.product.name
#     slug = slugify(title)
#     return "post_images/%s-%s" % (slug, filename)  


# class Images(models.Model):
#     product = models.ForeignKey(Product, default=None,related_name='images' , on_delete=models.CASCADE)
#     image = models.ImageField(upload_to=get_image_filename,verbose_name='Image')
    
    

src/cart/forms.py
from django import forms









PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,coerce=int)
    override = forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)

src/orders/forms.py
from django import forms
from .models import Order






class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['full_name','mobile_number', 'email', 'address', 'city']

src/cart/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from products.models import Product
from .cart import Cart
from .forms import CartAddProductForm



# def cart(request):
#     cart = Cart(request)
#     for item in cart:
#         item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],'override': True})
#     return render(request , 'cart/cart.html', {'cart': cart})

def cart(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(Products=product,quantity=cd['quantity'],override_quantity=cd['override'])
    return redirect('cart:cart')

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart')

src/orders/views.py
from django.shortcuts import render
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart








def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,product=item['product'],price=item['price'],quantity=item['quantity'])
            cart.clear()
            return render(request,'orders/order/created.html',{'order': order})
    else:
        form = OrderCreateForm()
    return render(request,'orders/order/create.html',{'cart': cart, 'form': form})

src/products/views.py
from django.shortcuts import render , get_object_or_404
from .models import Category , Product
from cart.forms import CartAddProductForm
from django.core.paginator import Paginator




def index(request):
    q = request.GET.get('q')
    categories = Category.objects.all()
    if q :
        products = Product.objects.filter(available=True , category__slug=q)
        paginator = Paginator(products , 25)
        page_number = request.GET.get('page')
        products = paginator.get_page(page_number)
    else:
        products = Product.objects.filter(available=True)
        paginator = Paginator(products , 25)
        page_number = request.GET.get('page')
        products = paginator.get_page(page_number)
    cart_product_form = CartAddProductForm()
    context = {'categories':categories ,'products':products,'cart_product_form':cart_product_form}
    return render(request , 'products/index.html' , context)



def product_detail(request , product_slug , cat_slug=None ):
    product = get_object_or_404(Product , slug=product_slug)
    cart_product_form = CartAddProductForm()
    context ={'product':product ,'cart_product_form':cart_product_form}
    return render(request , 'products/product_detail.html' , context)

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<!--
Template: Metronic Frontend Freebie - Responsive HTML Template Based On Twitter Bootstrap 3.3.4
Version: 1.0.0
Author: KeenThemes
Website: http://www.keenthemes.com/
Contact: support@keenthemes.com
Follow: www.twitter.com/keenthemes
Like: www.facebook.com/keenthemes
Purchase Premium Metronic Admin Theme: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
-->
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->

<!-- Head BEGIN -->
<head>
  <meta charset="utf-8">
  <title>Metronic Shop UI</title>

  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <meta content="Metronic Shop UI description" name="description">
  <meta content="Metronic Shop UI keywords" name="keywords">
  <meta content="keenthemes" name="author">

  <meta property="og:site_name" content="-CUSTOMER VALUE-">
  <meta property="og:title" content="-CUSTOMER VALUE-">
  <meta property="og:description" content="-CUSTOMER VALUE-">
  <meta property="og:type" content="website">
  <meta property="og:image" content="-CUSTOMER VALUE-"><!-- link to image for socio -->
  <meta property="og:url" content="-CUSTOMER VALUE-">

  <link rel="shortcut icon" href="favicon.ico">

  <!-- Fonts START -->
  <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700|PT+Sans+Narrow|Source+Sans+Pro:200,300,400,600,700,900&amp;subset=all" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900&amp;subset=all" rel="stylesheet" type="text/css"><!--- fonts for slider on the index page -->  
  <!-- Fonts END -->

  <!-- Global styles START -->          
  <link href="{% static 'assets/plugins/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Global styles END --> 
   
  <!-- Page level plugin styles START -->
  <link href="{% static 'assets/pages/css/animate.css' %}" rel="stylesheet">
  <link href="{% static 'assets/plugins/fancybox/source/jquery.fancybox.css' %}" rel="stylesheet">
  <link href="{% static 'assets/plugins/owl.carousel/assets/owl.carousel.css' %}" rel="stylesheet">
  <!-- Page level plugin styles END -->

  <!-- Theme styles START -->
  <link href="{% static 'assets/pages/css/components.css' %}" rel="stylesheet">
  <link href="{% static 'assets/pages/css/slider.css' %}" rel="stylesheet">
  <link href="{% static 'assets/pages/css/style-shop.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'assets/corporate/css/style.css' %}" rel="stylesheet">
  <link href="{% static 'assets/corporate/css/style-responsive.css' %}" rel="stylesheet">
  <link href="{% static 'assets/corporate/css/themes/red.css' %}" rel="stylesheet" id="style-color">
  <link href="{% static 'assets/corporate/css/custom.css' %}" rel="stylesheet">
  <!-- Theme styles END -->
</head>
<!-- Head END -->

<!-- Body BEGIN -->
<body class="ecommerce">
    
       <!-- BEGIN HEADER -->
       <div class="header">
        <div class="container">
          <a class="site-logo" href="{% url 'products:index' %}"><img src="{% static 'site_images/1.png' %}" alt="Metronic Shop UI" ></a>
      
          <a href="javascript:void(0);" class="mobi-toggler"><i class="fa fa-bars"></i></a>
      
          <!-- BEGIN CART -->
          <div class="top-cart-block">
            <div class="top-cart-info">
              <a href="javascript:void(0);" class="top-cart-info-count">{% with total_items=cart|length %}
                {% if total_items > 0 %}
                <a href="{% url 'cart:cart' %}">
                {{ total_items }} item{{ total_items|pluralize }},
                <a href="javascript:void(0);" class="top-cart-info-value">${{ cart.get_total_price }}</a>
                </a>
                {% else %}
                Your cart is empty.
                {% endif %}
                {% endwith %}</a>
            </div>
            <i class="fa fa-shopping-cart"></i>
            <div class="top-cart-content-wrapper">
              <div class="top-cart-content">
                <ul class="scroller" style="height: 250px;">
                  {% for item in cart %}
                    {% with product=item.product %}
                  <li>
                    <a href="#"><img src="{{ product.image.url}}" alt="Rolex Classic Watch" width="37" height="34"></a>
                    <span class="cart-content-count">x {{ item.quantity }}</span>
                    <strong><a href="shop-item.html">{{ product.name }}</a></strong>
                    <em>{{ item.price }}</em>
                    <form action="{% url "cart:cart_remove" product.id %}"method="post"><input type="submit" value="Remove">
                      {% csrf_token %}
                    </form>
                    {% comment %} <a href="javascript:void(0);" class="del-goods">&nbsp;</a> {% endcomment %}
                  </li>
                  {% endwith %}
                {% endfor %}
                </ul>
                <div class="text-right">
                  <a href="{% url 'cart:cart' %}" class="btn btn-default">View Cart</a>
                  <a href="shop-checkout.html" class="btn btn-primary">Checkout</a>
                </div>
              </div>
            </div>            
          </div>
          <!--END CART -->
      
          <!-- BEGIN NAVIGATION -->
          <div class="header-navigation">
            <ul>
              <li class=""><a  href="{% url 'products:index' %}"> Home </a></li>
              {% comment %} <li class="dropdown dropdown-megamenu">
                <a class="dropdown-toggle" data-toggle="dropdown" data-target="#" href="javascript:;">Categories</a>
                <ul class="col-md-2 dropdown-menu">
                  <li>
                    <div class="header-navigation-content">
                      <div class="row">
                        {% for c in categories %}
                        <div class="col-md-3 header-navigation-col">
                          <h4>{{c}}</h4>
                          {% for sup in sup_categories %}
                          {% if sup.category == c %}
                          <ul>
                            <li class="m-t-3"><a href="{% url 'products:by_supcategory' c.slug sup.slug %}">{{sup}}</a></li>
                          </ul>
                          {% endif %}
                          {% endfor %}
                          {% endfor %}
                        </div>
                      </div>
                    </div>
                  </li>
                </ul>
              </li> {% endcomment %}
              <li><a href="shop-item.html">My wishlist</a></li>
              <li><a href="shop-item.html">My Account</a></li>
              <li><a href="{% url 'cart:cart' %}">Cart</a></li>
              <li><a href="" >{% if request.user.is_authenticated %}{{ user }}{% else %}Login{% endif %}</a></li>
              <!-- BEGIN TOP SEARCH -->
              <li class="menu-search">
                <span class="sep"></span>
                <i class="fa fa-search search-btn"></i>
                <div class="search-box">
                  <form action="#">
                    <div class="input-group">
                      <input type="text" placeholder="Search" class="form-control">
                      <span class="input-group-btn">
                        <button class="btn btn-primary" type="submit">Search</button>
                      </span>
                    </div>
                  </form>
                </div> 
              </li>
              <!-- END TOP SEARCH -->
            </ul>
          </div>
          <!-- END NAVIGATION -->
        </div>
      </div>
      <!-- Header END -->
  

    {% block body %}
    
    {% endblock body %}

    
    <!-- BEGIN FOOTER -->
    <div class="footer" style ="position: fixed;left: 0;bottom: 0;width: 100%;">
      <div class="container">
        <div class="row">
          <!-- BEGIN COPYRIGHT -->
          <div class="col-md-4 col-sm-4 padding-top-10">
            2015 © Keenthemes. ALL Rights Reserved. 
          </div>
          <!-- END COPYRIGHT -->

          <!-- BEGIN POWERED -->
          <div class="col-md-4 col-sm-4 text-right">
            <p class="powered">Powered by: <a href="http://www.MostafaSaad.com/">Mostaf@saad</a></p>
          </div>
          <!-- END POWERED -->
        </div>
      </div>
    </div>
    <!-- END FOOTER -->
    <!-- Load javascripts at bottom, this will reduce page load time -->
    <!-- BEGIN CORE PLUGINS (REQUIRED FOR ALL PAGES) -->
    <!--[if lt IE 9]>
    <script src="assets/plugins/respond.min.js"></script>  
    <![endif]-->
    <script src="{% static 'assets/plugins/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/plugins/jquery-migrate.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>      
    <script src="{% static 'assets/corporate/scripts/back-to-top.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js' %}" type="text/javascript"></script>
    <!-- END CORE PLUGINS -->

    <!-- BEGIN PAGE LEVEL JAVASCRIPTS (REQUIRED ONLY FOR CURRENT PAGE) -->
    <script src="{% static 'assets/plugins/fancybox/source/jquery.fancybox.pack.js' %}" type="text/javascript"></script><!-- pop up -->
    <script src="{% static 'assets/plugins/owl.carousel/owl.carousel.min.js' %}" type="text/javascript"></script><!-- slider for products -->
    <script src="{% static 'assets/plugins/zoom/jquery.zoom.min.js' %}" type="text/javascript"></script><!-- product zoom -->
    <script src="{% static 'assets/plugins/bootstrap-touchspin/bootstrap.touchspin.js' %}" type="text/javascript"></script><!-- Quantity -->

    <script src="{% static 'assets/corporate/scripts/layout.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/pages/scripts/bs-carousel.js' %}" type="text/javascript"></script>
    <script type="text/javascript">
        jQuery(document).ready(function() {
            Layout.init();    
            Layout.initOWL();
            Layout.initImageZoom();
            Layout.initTouchspin();
            Layout.initTwitter();
        });
    </script>
    <!-- END PAGE LEVEL JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>

src/templates/cart/detail.html
{% extends 'base.html' %}

{% block body %}

<div class="main">
  <div class="container">
    <!-- BEGIN SIDEBAR & CONTENT -->
    <div class="row margin-bottom-40">
      <!-- BEGIN CONTENT -->
      <div class="col-md-12 col-sm-12">
        <h1>Shopping cart</h1>
        <div class="goods-page">
          <div class="goods-data clearfix">
            <div class="table-wrapper-responsive">
            <table summary="Shopping cart">
              <thead>
              <tr>
                <th class="goods-page-image">Image</th>
                <th class="goods-page-description">Description</th>
                <th class="goods-page-quantity">Quantity</th>
                <th class="goods-page-price">Unit price</th>
                <th class="goods-page-total" colspan="2">Total</th>
              </tr>
            </thead>
            <tbody>
              
              {% for item in cart %}
                {% with product=item.product %}
                  <tr>
                    <td class="goods-page-image">
                      <a href="javascript:;"><img src="{{product.image.url}}" alt="Berry Lace Dress"></a>
                    </td>
                    <td class="goods-page-description">
                      <h3><a href="javascript:;">{{product.name}}</a></h3>
                      
                      <em>{{product.description}}</em>
                    </td>
                    <td class="goods-page-quantity">
                      <form action="{% url 'cart:cart_add' product.id %}" method="post">
                        {{ item.update_quantity_form.quantity }}
                        {{ item.update_quantity_form.override }}
                        <input type="submit" value="Update">
                        {% csrf_token %}
                        </form>
                    </td>
                    <td class="goods-page-price">
                      <strong><span>$</span>{{product.price}}</strong>
                    </td>
                    <td class="goods-page-total">
                      <strong><span>$</span>{{item.total_price}}</strong>
                    </td>
                    <td class="del-goods-col">
                      <form action="{% url 'cart:cart_remove' product.id %}"method="post">
                        <button><i class="fa fa-trash"></i>Remove</button>
                        {% csrf_token %}
                        </form>
                      {% comment %} <a class="del-goods" href="javascript:;">&nbsp;</a> {% endcomment %}
                    </td>
                  </tr>
                {% endwith %}
              {% endfor %}
            </tbody>
            </table>
            </div>
            <div class="shopping-total">
              <ul>
                <li>
                  <em>Sub total</em>
                  <strong class="price"><span>$</span>{{item.total_price}}</strong>
                </li>
                <li>
                  <em>Shipping cost</em>
                  <strong id='ship' class="price"><span></span>Free for awhile</strong>
                </li>
                <li class="shopping-total-price">
                  <em>Total</em>
                  <strong class="price"><span>$</span>{{cart.get_total_price}}</strong>
                </li>
              </ul>
            </div>
          </div>
          <a a href="{% url 'products:index' %}">
        <button class="btn btn-default" type="submit">Continue shopping <i class="fa fa-shopping-cart"></i></button>
          </a>
          <a href = "{% url 'orders:order_create' %}">
        <button class="btn btn-primary" type="submit" >Checkout <i class="fa fa-check"></i></button>
          </a>
    </div>
  </div>
</div>

{% endblock body %}

src/templates/orders/order/created.html
{% extends 'base.html' %}


{% block body %}
<h1>Thank you</h1>
<p>Your order has been successfully completed. Your order number is
<strong>{{ order.id }}</strong>.</p>
{% endblock %}

src/templates/products/index.html
{% extends 'base.html' %}


{% block body %}



  <div class="main">
    <div class="container">
      <!-- BEGIN SIDEBAR & CONTENT -->
      <div class="row margin-bottom-40">
        <!-- BEGIN SIDEBAR -->
        <div class="row margin-bottom-40 ">
            <!-- BEGIN SIDEBAR -->
            <div class="sidebar col-md-3 col-sm-4">
              <ul class="list-group margin-bottom-25 sidebar-menu">
                <li><h4>Categories</h4></li>
                <a href="{% url 'products:index' %}"><h4>All</h4>
                {%for c in categories %}
                  {% if category == c.slug %} {% endif %}
                    <li class="list-group-item clearfix dropdown "><a href="{% url 'products:index'%}?q={{c.slug}}"><i class="fa fa-angle-right"></i>{{c}}</a></li>
                {% endfor %}
              </ul>
          <div class="sidebar-filter margin-bottom-25">
            <h2>Filter</h2>
            <h3>Availability</h3>
            <div class="checkbox-list">
              <label><input type="checkbox"> Not Available (3)</label>
              <label><input type="checkbox"> In Stock (26)</label>
            </div>

            <h3>Price</h3>
            <p>
              <label for="amount">Range:</label>
              <input type="text" id="amount" style="border:0; color:#f6931f; font-weight:bold;">
            </p>
            <div id="slider-range"></div>
          </div>
        </div>
        <!-- END SIDEBAR -->
        <!-- BEGIN CONTENT -->
        <div class="col-md-9 col-sm-7">
          <div class="row list-view-sorting clearfix">
            <div class="col-md-2 col-sm-2 list-view">
              <a href="javascript:;"><i class="fa fa-th-large"></i></a>
              <a href="javascript:;"><i class="fa fa-th-list"></i></a>
            </div>
            <div class="col-md-10 col-sm-10">
              <div class="pull-right">
                <label class="control-label">Show:</label>
                <select class="form-control input-sm">
                  <option><a href="{% url 'products:index'%}?show=25"></a>25</option>
                  <option><a href="{% url 'products:index'%}?show=50"></a>50</option>
                  <option><a href="{% url 'products:index'%}?show=75"></a>75</option>
                  <option><a href="{% url 'products:index'%}?show=100"></a>100</option>
                </select>
              </div>
              <div class="pull-right">
                <label class="control-label">Sort&nbsp;By:</label>
                <select class="form-control input-sm">
                  <option value="#?sort=p.sort_order&amp;order=ASC" selected="selected">Default</option>
                  <option value="#?sort=pd.name&amp;order=ASC">Name (A - Z)</option>
                  <option value="#?sort=pd.name&amp;order=DESC">Name (Z - A)</option>
                  <option value="#?sort=p.price&amp;order=ASC">Price (Low &gt; High)</option>
                  <option value="#?sort=p.price&amp;order=DESC">Price (High &gt; Low)</option>
                  <option value="#?sort=rating&amp;order=DESC">Rating (Highest)</option>
                  <option value="#?sort=rating&amp;order=ASC">Rating (Lowest)</option>
                  <option value="#?sort=p.model&amp;order=ASC">Model (A - Z)</option>
                  <option value="#?sort=p.model&amp;order=DESC">Model (Z - A)</option>
                </select>
              </div>
            </div>
          </div>
          <!-- BEGIN PRODUCT LIST -->
          <div class="row product-list">
            <!-- PRODUCT ITEM START -->
            {% for product in products%}
              <div class="col-md-4 col-sm-6 col-xs-12">
                <div class="product-item">
                  <div class="pi-img-wrapper">
                    <img src="{{product.image.url}}" style="width:300px;height:250px;" class="img-responsive" alt="Berry Lace Dress">
                    <div>
                      <a href="{{product.image.url}}" class="btn btn-default fancybox-button">Zoom</a>
                      <a href="{% url 'products:product_detail' product.category.slug product.slug %}" class="btn btn-default fancybox-fast-view">View</a>
                    </div>
                  </div>
                  <h3><a href="{% url 'products:product_detail' product.category.slug product.slug %}">{{product}}</a></h3>
                  <div class="pi-price">{{product.price}}</div>
                    <form action="{% url 'cart:cart_add' product.id %}" method="post">
                      {{ cart_product_form }}
                        {% csrf_token %}
                      <input type="submit" class="btn btn-default add2cart" value="Add to cart">
                  </form>
                  {% comment %} <a href="javascript:;" class="btn btn-default add2cart">Add to cart</a> {% endcomment %}
                </div>
              </div>
            {% endfor %}

            <!-- PRODUCT ITEM END -->        
          </div>

          <!-- END PRODUCT LIST -->
          <!-- BEGIN PAGINATOR -->
          <div class="row">
            <div class="col-md-6 col-sm-8">
              <ul class="pagination pull-right">
                {% if products.has_previous %}
                <li><a href="?page={{ products.previous_page_number }}">&laquo;</a></li>
                {% endif %}
                <li><span>Page {{ products.number }}of {{ products.paginator.num_pages }} Pages</span></li>
                {% if products.has_next %}
                <li><a href="?page={{ products.next_page_number }}">&raquo;</a></li>
                {% endif %}
              </ul>
            </div>
          </div>
          <!-- END PAGINATOR -->
        </div>
        <!-- END CONTENT -->
      </div>
      <!-- END SIDEBAR & CONTENT -->
    </div>
  </div>

{% endblock body %}